# example netlify.toml
[build]
  command = "gatsby build"
  functions = "functions"
  publish = "public"

[build.environment]
  NETLIFY_BUILD_DEBUG = "true"

[context.monorepo]
  base = "packages/blog-1"

[context.monorepo.environment]
  NETLIFY_USE_YARN = "true"

[[redirects]]
  # Telemetry link
  from = "/telemetry/track"
  to = "https://test-ntl-functions.netlify.app/.netlify/functions/track"
  status = 200
  force = false
[[redirects]]
   # Telemetry link
  from = "/telemetry/identify"
  to = "https://test-ntl-functions.netlify.app/.netlify/functions/identify"
  status = 200
  force = false

  ## Uncomment to use this redirect for Single Page Applications like create-react-app.
  ## Not needed for static site generators.
  #[[redirects]]
  #  from = "/*"
  #  to = "/index.html"
  #  status = 200

  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/master/docs/netlify-dev.md#project-detection
  #[dev]
  #  command = "yarn start" # Command to start your dev server
  #  port = 3000 # Port that the dev server will be listening on
  #  publish = "dist" # Folder with the static content for _redirect file

  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/
